---
## Service
apiVersion: v1
kind: Service
metadata:
  name: tomcat
  namespace: tomcat
spec:
  type: NodePort
  selector:
    app: tomcat
  ports:
    - name: tomcat
      port: 80
      protocol: TCP
      targetPort: 8080
      nodePort: 32227

---
## Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat
  namespace: tomcat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
        - name: tomcat
          image: gcr.io/kodekloud/centos-ssh-enabled:tomcat
          ports:
            - containerPort: 8080
