---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: mongo
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/ubuntu/pv/mongo_data"
