-- MySQL Script generated by MySQL Workbench
-- Fri Jan 13 15:33:20 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema shopping
-- -----------------------------------------------------
-- a small version of online shopping database like amazon.
DROP SCHEMA IF EXISTS `shopping` ;

-- -----------------------------------------------------
-- Schema shopping
--
-- a small version of online shopping database like amazon.
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shopping` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `shopping` ;

-- -----------------------------------------------------
-- Table `shopping`.`addresses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shopping`.`addresses` ;

CREATE TABLE IF NOT EXISTS `shopping`.`addresses` (
  `address_id` INT NOT NULL AUTO_INCREMENT,
  `street` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `province` VARCHAR(45) NOT NULL,
  `postal_code` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`address_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopping`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shopping`.`categories` ;

CREATE TABLE IF NOT EXISTS `shopping`.`categories` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL DEFAULT 'no category',
  PRIMARY KEY (`category_id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopping`.`items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shopping`.`items` ;

CREATE TABLE IF NOT EXISTS `shopping`.`items` (
  `item_id` INT NOT NULL AUTO_INCREMENT,
  `seller_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `price` DECIMAL(8,2) NOT NULL DEFAULT 0.00,
  `quantity` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`item_id`, `seller_id`, `product_id`),
  INDEX `fk_items_sellers1_idx` (`seller_id` ASC) VISIBLE,
  INDEX `fk_items_products1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_items_sellers1`
    FOREIGN KEY (`seller_id`)
    REFERENCES `shopping`.`sellers` (`seller_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_items_products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `shopping`.`products` (`product_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopping`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shopping`.`orders` ;

CREATE TABLE IF NOT EXISTS `shopping`.`orders` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `address_id` INT NULL,
  `payment_method_id` INT NULL,
  `order_date` DATE NULL,
  PRIMARY KEY (`order_id`),
  INDEX `fk_orders_addresses1_idx` (`address_id` ASC) VISIBLE,
  INDEX `fk_orders_payment_methods1_idx` (`payment_method_id` ASC) VISIBLE,
  CONSTRAINT `fk_orders_addresses1`
    FOREIGN KEY (`address_id`)
    REFERENCES `shopping`.`addresses` (`address_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_orders_payment_methods1`
    FOREIGN KEY (`payment_method_id`)
    REFERENCES `shopping`.`payment_methods` (`payment_method_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopping`.`orders_shopping_cart_lines`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shopping`.`orders_shopping_cart_lines` ;

CREATE TABLE IF NOT EXISTS `shopping`.`orders_shopping_cart_lines` (
  `order_id` INT NOT NULL,
  `shopping_cart_line_id` INT NOT NULL,
  INDEX `fk_order_details_shopping_cart_lines1_idx` (`shopping_cart_line_id` ASC) VISIBLE,
  PRIMARY KEY (`order_id`, `shopping_cart_line_id`),
  INDEX `fk_shopping_carts_orders1_idx` (`order_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_details_shopping_cart_lines1`
    FOREIGN KEY (`shopping_cart_line_id`)
    REFERENCES `shopping`.`shopping_cart_lines` (`shopping_cart_line_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_shopping_carts_orders1`
    FOREIGN KEY (`order_id`)
    REFERENCES `shopping`.`orders` (`order_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopping`.`payment_method_categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shopping`.`payment_method_categories` ;

CREATE TABLE IF NOT EXISTS `shopping`.`payment_method_categories` (
  `payment_method_category_id` INT NOT NULL AUTO_INCREMENT,
  `payment_method_category_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`payment_method_category_id`),
  UNIQUE INDEX `payment_method_category_name_UNIQUE` (`payment_method_category_name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopping`.`payment_methods`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shopping`.`payment_methods` ;

CREATE TABLE IF NOT EXISTS `shopping`.`payment_methods` (
  `payment_method_id` INT NOT NULL AUTO_INCREMENT,
  `payment_method_category_id` INT NOT NULL,
  `name_on_card` VARCHAR(45) NOT NULL,
  `card_number` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`payment_method_id`, `payment_method_category_id`),
  UNIQUE INDEX `card_number_UNIQUE` (`card_number` ASC) VISIBLE,
  INDEX `fk_payment_methods_payment_method_categories1_idx` (`payment_method_category_id` ASC) VISIBLE,
  CONSTRAINT `fk_payment_methods_payment_method_categories1`
    FOREIGN KEY (`payment_method_category_id`)
    REFERENCES `shopping`.`payment_method_categories` (`payment_method_category_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopping`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shopping`.`products` ;

CREATE TABLE IF NOT EXISTS `shopping`.`products` (
  `product_id` INT NOT NULL AUTO_INCREMENT,
  `category_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`product_id`, `category_id`),
  INDEX `fk_products_categories1_idx` (`category_id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  CONSTRAINT `fk_products_categories1`
    FOREIGN KEY (`category_id`)
    REFERENCES `shopping`.`categories` (`category_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopping`.`sellers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shopping`.`sellers` ;

CREATE TABLE IF NOT EXISTS `shopping`.`sellers` (
  `seller_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`seller_id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopping`.`shopping_cart_lines`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shopping`.`shopping_cart_lines` ;

CREATE TABLE IF NOT EXISTS `shopping`.`shopping_cart_lines` (
  `shopping_cart_line_id` INT NOT NULL AUTO_INCREMENT,
  `item_id` INT NOT NULL,
  `quantity` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`shopping_cart_line_id`, `item_id`),
  INDEX `fk_shopping_cart_lines_items1_idx` (`item_id` ASC) VISIBLE,
  CONSTRAINT `fk_shopping_cart_lines_items1`
    FOREIGN KEY (`item_id`)
    REFERENCES `shopping`.`items` (`item_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
