---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: nginx
spec:
  type: NodePort
  selector:
    app: nginx
    type: front-end
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30008
